server:
  port: 8081

spring:
  application:
    name: Fraud
  datasource:
    url: jdbc:mysql://mysql:3306/amigoscode?allowPublicKeyRetrieval=true&useSSL=false
    username: amigoscode
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true