#application name
spring:
  application:
    name: api-gateway

#https://stackoverflow.com/questions/68587832/spring-cloud-gateway-spring-mvc-found-on-classpath-which-is-incompatible-with
  main:
    web-application-type: reactive

  #zipkin configuration
  zipkin:
    base-url: http://localhost:9411

  #api-gateway routes configuration
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**


#application server port configuration
server:
  port: 8082

#Eureka server configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true