server:
  port: 8083

spring:
  application:
    name: Notification
  datasource:
    #https://stackoverflow.com/questions/50379839/connection-java-mysql-public-key-retrieval-is-not-allowed
    url: jdbc:mysql://mysql:3306/amigoscode?allowPublicKeyRetrieval=true&useSSL=false
    username: amigoscode
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key